using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameResultHandler : MonoBehaviour
{
    private void OnEnable()
    {
        NewSpawner.OnDemonVictory += HandleVictory;
        NewSpawner.OnDemonDefeat += HandleDefeat;
    }

    private void OnDisable()
    {
        NewSpawner.OnDemonVictory -= HandleVictory;
        NewSpawner.OnDemonDefeat -= HandleDefeat;
    }

    private void HandleVictory()
    {
        Debug.Log("üéä ¬°VICTORIA DEMON√çACA!");
        // UIManager.Instance?.ShowVictoryPanel();
        // Time.timeScale = 0;
    }

    private void HandleDefeat()
    {
        Debug.Log("üíî DERROTA DEMON√çACA...");
        // UIManager.Instance?.ShowDefeatPanel();
        // Time.timeScale = 0;
    }
}
